// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package UsersService

import (
	context "context"
	error1 "github.com/zytell3301/tg-users-service/pkg/error"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersServiceClient interface {
	NewUser(ctx context.Context, in *NewUserMessage, opts ...grpc.CallOption) (*error1.Error, error)
	DeleteUser(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*error1.Error, error)
	UpdateUsername(ctx context.Context, in *UpdateUsernameMessage, opts ...grpc.CallOption) (*error1.Error, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RequestSignupSecurityCode(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*error1.Error, error)
	RequestLoginSecurityCode(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*error1.Error, error)
	VerifySecurityCode(ctx context.Context, in *VerifySecurityCodeRequest, opts ...grpc.CallOption) (*error1.Error, error)
	GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*GetUserByUsernameResponse, error)
}

type usersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceClient(cc grpc.ClientConnInterface) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) NewUser(ctx context.Context, in *NewUserMessage, opts ...grpc.CallOption) (*error1.Error, error) {
	out := new(error1.Error)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*error1.Error, error) {
	out := new(error1.Error)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUsername(ctx context.Context, in *UpdateUsernameMessage, opts ...grpc.CallOption) (*error1.Error, error) {
	out := new(error1.Error)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/UpdateUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RequestSignupSecurityCode(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*error1.Error, error) {
	out := new(error1.Error)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/RequestSignupSecurityCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RequestLoginSecurityCode(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*error1.Error, error) {
	out := new(error1.Error)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/RequestLoginSecurityCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) VerifySecurityCode(ctx context.Context, in *VerifySecurityCodeRequest, opts ...grpc.CallOption) (*error1.Error, error) {
	out := new(error1.Error)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/VerifySecurityCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*GetUserByUsernameResponse, error) {
	out := new(GetUserByUsernameResponse)
	err := c.cc.Invoke(ctx, "/zytell3301.UsersService.UsersService/GetUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
// All implementations must embed UnimplementedUsersServiceServer
// for forward compatibility
type UsersServiceServer interface {
	NewUser(context.Context, *NewUserMessage) (*error1.Error, error)
	DeleteUser(context.Context, *Phone) (*error1.Error, error)
	UpdateUsername(context.Context, *UpdateUsernameMessage) (*error1.Error, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RequestSignupSecurityCode(context.Context, *Phone) (*error1.Error, error)
	RequestLoginSecurityCode(context.Context, *Phone) (*error1.Error, error)
	VerifySecurityCode(context.Context, *VerifySecurityCodeRequest) (*error1.Error, error)
	GetUserByUsername(context.Context, *GetUserByUsernameRequest) (*GetUserByUsernameResponse, error)
	mustEmbedUnimplementedUsersServiceServer()
}

// UnimplementedUsersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (UnimplementedUsersServiceServer) NewUser(context.Context, *NewUserMessage) (*error1.Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUser not implemented")
}
func (UnimplementedUsersServiceServer) DeleteUser(context.Context, *Phone) (*error1.Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUsersServiceServer) UpdateUsername(context.Context, *UpdateUsernameMessage) (*error1.Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUsername not implemented")
}
func (UnimplementedUsersServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUsersServiceServer) RequestSignupSecurityCode(context.Context, *Phone) (*error1.Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSignupSecurityCode not implemented")
}
func (UnimplementedUsersServiceServer) RequestLoginSecurityCode(context.Context, *Phone) (*error1.Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestLoginSecurityCode not implemented")
}
func (UnimplementedUsersServiceServer) VerifySecurityCode(context.Context, *VerifySecurityCodeRequest) (*error1.Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySecurityCode not implemented")
}
func (UnimplementedUsersServiceServer) GetUserByUsername(context.Context, *GetUserByUsernameRequest) (*GetUserByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUsername not implemented")
}
func (UnimplementedUsersServiceServer) mustEmbedUnimplementedUsersServiceServer() {}

// UnsafeUsersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServiceServer will
// result in compilation errors.
type UnsafeUsersServiceServer interface {
	mustEmbedUnimplementedUsersServiceServer()
}

func RegisterUsersServiceServer(s grpc.ServiceRegistrar, srv UsersServiceServer) {
	s.RegisterService(&UsersService_ServiceDesc, srv)
}

func _UsersService_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).NewUser(ctx, req.(*NewUserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Phone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteUser(ctx, req.(*Phone))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUsernameMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/UpdateUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateUsername(ctx, req.(*UpdateUsernameMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RequestSignupSecurityCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Phone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RequestSignupSecurityCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/RequestSignupSecurityCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RequestSignupSecurityCode(ctx, req.(*Phone))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RequestLoginSecurityCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Phone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RequestLoginSecurityCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/RequestLoginSecurityCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RequestLoginSecurityCode(ctx, req.(*Phone))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_VerifySecurityCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySecurityCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).VerifySecurityCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/VerifySecurityCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).VerifySecurityCode(ctx, req.(*VerifySecurityCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytell3301.UsersService.UsersService/GetUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserByUsername(ctx, req.(*GetUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersService_ServiceDesc is the grpc.ServiceDesc for UsersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zytell3301.UsersService.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUser",
			Handler:    _UsersService_NewUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersService_DeleteUser_Handler,
		},
		{
			MethodName: "UpdateUsername",
			Handler:    _UsersService_UpdateUsername_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UsersService_Login_Handler,
		},
		{
			MethodName: "RequestSignupSecurityCode",
			Handler:    _UsersService_RequestSignupSecurityCode_Handler,
		},
		{
			MethodName: "RequestLoginSecurityCode",
			Handler:    _UsersService_RequestLoginSecurityCode_Handler,
		},
		{
			MethodName: "VerifySecurityCode",
			Handler:    _UsersService_VerifySecurityCode_Handler,
		},
		{
			MethodName: "GetUserByUsername",
			Handler:    _UsersService_GetUserByUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/UsersService/users-service.proto",
}
