// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.12.4
// source: api/pb/UsersService/users-service.proto

package UsersService

import (
	error1 "github.com/zytell3301/tg-users-service/pkg/error"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUsernameMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone    string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *UpdateUsernameMessage) Reset() {
	*x = UpdateUsernameMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_UsersService_users_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsernameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameMessage) ProtoMessage() {}

func (x *UpdateUsernameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_UsersService_users_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameMessage.ProtoReflect.Descriptor instead.
func (*UpdateUsernameMessage) Descriptor() ([]byte, []int) {
	return file_api_pb_UsersService_users_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUsernameMessage) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUsernameMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NewUserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User         `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	SecurityCode *SecurityCode `protobuf:"bytes,2,opt,name=SecurityCode,proto3" json:"SecurityCode,omitempty"`
}

func (x *NewUserMessage) Reset() {
	*x = NewUserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_UsersService_users_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserMessage) ProtoMessage() {}

func (x *NewUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_UsersService_users_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserMessage.ProtoReflect.Descriptor instead.
func (*NewUserMessage) Descriptor() ([]byte, []int) {
	return file_api_pb_UsersService_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *NewUserMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *NewUserMessage) GetSecurityCode() *SecurityCode {
	if x != nil {
		return x.SecurityCode
	}
	return nil
}

type Phone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
}

func (x *Phone) Reset() {
	*x = Phone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_UsersService_users_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_UsersService_users_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_api_pb_UsersService_users_service_proto_rawDescGZIP(), []int{2}
}

func (x *Phone) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Lastname     string `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Bio          string `protobuf:"bytes,4,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Username     string `protobuf:"bytes,5,opt,name=Username,proto3" json:"Username,omitempty"`
	Phone        string `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	OnlineStatus bool   `protobuf:"varint,7,opt,name=Online_status,json=OnlineStatus,proto3" json:"Online_status,omitempty"`
	CreatedAt    int64  `protobuf:"varint,8,opt,name=Created_at,json=CreatedAt,proto3" json:"Created_at,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_UsersService_users_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_UsersService_users_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_pb_UsersService_users_service_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetOnlineStatus() bool {
	if x != nil {
		return x.OnlineStatus
	}
	return false
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SecurityCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *SecurityCode) Reset() {
	*x = SecurityCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_UsersService_users_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityCode) ProtoMessage() {}

func (x *SecurityCode) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_UsersService_users_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityCode.ProtoReflect.Descriptor instead.
func (*SecurityCode) Descriptor() ([]byte, []int) {
	return file_api_pb_UsersService_users_service_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_api_pb_UsersService_users_service_proto protoreflect.FileDescriptor

var file_api_pb_UsersService_users_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x7a, 0x79, 0x74, 0x65, 0x6c,
	0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8e,
	0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x31, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x7a, 0x79, 0x74, 0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x7a, 0x79, 0x74,
	0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x0c, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x1d, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0xce,
	0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x22, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x32, 0xfd, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x27, 0x2e, 0x7a, 0x79, 0x74, 0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x7a, 0x79, 0x74, 0x65, 0x6c,
	0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x45, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x1e, 0x2e, 0x7a, 0x79, 0x74, 0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x1a,
	0x17, 0x2e, 0x7a, 0x79, 0x74, 0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x59, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x7a, 0x79, 0x74,
	0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x7a, 0x79, 0x74,
	0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x7a, 0x79, 0x74, 0x65, 0x6c, 0x6c, 0x33, 0x33, 0x30, 0x31, 0x2f, 0x74, 0x67, 0x2d,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pb_UsersService_users_service_proto_rawDescOnce sync.Once
	file_api_pb_UsersService_users_service_proto_rawDescData = file_api_pb_UsersService_users_service_proto_rawDesc
)

func file_api_pb_UsersService_users_service_proto_rawDescGZIP() []byte {
	file_api_pb_UsersService_users_service_proto_rawDescOnce.Do(func() {
		file_api_pb_UsersService_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pb_UsersService_users_service_proto_rawDescData)
	})
	return file_api_pb_UsersService_users_service_proto_rawDescData
}

var file_api_pb_UsersService_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_pb_UsersService_users_service_proto_goTypes = []interface{}{
	(*UpdateUsernameMessage)(nil), // 0: zytell3301.UsersService.UpdateUsernameMessage
	(*NewUserMessage)(nil),        // 1: zytell3301.UsersService.NewUserMessage
	(*Phone)(nil),                 // 2: zytell3301.UsersService.Phone
	(*User)(nil),                  // 3: zytell3301.UsersService.User
	(*SecurityCode)(nil),          // 4: zytell3301.UsersService.SecurityCode
	(*error1.Error)(nil),          // 5: zytell3301.error.Error
}
var file_api_pb_UsersService_users_service_proto_depIdxs = []int32{
	3, // 0: zytell3301.UsersService.NewUserMessage.User:type_name -> zytell3301.UsersService.User
	4, // 1: zytell3301.UsersService.NewUserMessage.SecurityCode:type_name -> zytell3301.UsersService.SecurityCode
	1, // 2: zytell3301.UsersService.UsersService.NewUser:input_type -> zytell3301.UsersService.NewUserMessage
	2, // 3: zytell3301.UsersService.UsersService.DeleteUser:input_type -> zytell3301.UsersService.Phone
	0, // 4: zytell3301.UsersService.UsersService.UpdateUsername:input_type -> zytell3301.UsersService.UpdateUsernameMessage
	5, // 5: zytell3301.UsersService.UsersService.NewUser:output_type -> zytell3301.error.Error
	5, // 6: zytell3301.UsersService.UsersService.DeleteUser:output_type -> zytell3301.error.Error
	5, // 7: zytell3301.UsersService.UsersService.UpdateUsername:output_type -> zytell3301.error.Error
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_pb_UsersService_users_service_proto_init() }
func file_api_pb_UsersService_users_service_proto_init() {
	if File_api_pb_UsersService_users_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pb_UsersService_users_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsernameMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_UsersService_users_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_UsersService_users_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_UsersService_users_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_UsersService_users_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pb_UsersService_users_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_UsersService_users_service_proto_goTypes,
		DependencyIndexes: file_api_pb_UsersService_users_service_proto_depIdxs,
		MessageInfos:      file_api_pb_UsersService_users_service_proto_msgTypes,
	}.Build()
	File_api_pb_UsersService_users_service_proto = out.File
	file_api_pb_UsersService_users_service_proto_rawDesc = nil
	file_api_pb_UsersService_users_service_proto_goTypes = nil
	file_api_pb_UsersService_users_service_proto_depIdxs = nil
}
